all: copy seek_io

copy:

pipe_sync:

seek_io:

sun_stream_client:

sun_stream_server:

t_readv:

clean:
	$(RM) copy pipe_sync seek_io sun_stream_client sun_stream_server t_readv

test_copy: copy
	./test_copy

test_seek_io: seek_io
	./test_seek_io

test_t_readv: t_readv
	./test_t_readv
